/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'
import { Route as ReviewsCheckIdRouteImport } from './routes/reviews.$checkId'
import { Route as BrandsBrandIdIndexRouteImport } from './routes/brands.$brandId.index'
import { Route as BrandsBrandIdBrainRouteImport } from './routes/brands.$brandId.brain'
import { Route as BrandsBrandIdReviewRouteImport } from './routes/brands.$brandId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsCheckIdRoute = ReviewsCheckIdRouteImport.update({
  id: '/reviews/$checkId',
  path: '/reviews/$checkId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdIndexRoute = BrandsBrandIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsBrandIdRoute,
} as any)
const BrandsBrandIdBrainRoute = BrandsBrandIdBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => BrandsBrandIdRoute,
} as any)
const BrandsBrandIdReviewRoute = BrandsBrandIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => BrandsBrandIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands/$brandId': typeof BrandsBrandIdRouteWithChildren
  '/reviews/$checkId': typeof ReviewsCheckIdRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/review': typeof BrandsBrandIdReviewRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviews/$checkId': typeof ReviewsCheckIdRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/review': typeof BrandsBrandIdReviewRoute
  '/brands/$brandId': typeof BrandsBrandIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands/$brandId': typeof BrandsBrandIdRouteWithChildren
  '/reviews/$checkId': typeof ReviewsCheckIdRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/review': typeof BrandsBrandIdReviewRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands/$brandId'
    | '/reviews/$checkId'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/review'
    | '/brands/$brandId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reviews/$checkId'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/review'
    | '/brands/$brandId'
  id:
    | '__root__'
    | '/'
    | '/brands/$brandId'
    | '/reviews/$checkId'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/review'
    | '/brands/$brandId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRouteWithChildren
  ReviewsCheckIdRoute: typeof ReviewsCheckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$checkId': {
      id: '/reviews/$checkId'
      path: '/reviews/$checkId'
      fullPath: '/reviews/$checkId'
      preLoaderRoute: typeof ReviewsCheckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/': {
      id: '/brands/$brandId/'
      path: '/'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof BrandsBrandIdIndexRouteImport
      parentRoute: typeof BrandsBrandIdRoute
    }
    '/brands/$brandId/brain': {
      id: '/brands/$brandId/brain'
      path: '/brain'
      fullPath: '/brands/$brandId/brain'
      preLoaderRoute: typeof BrandsBrandIdBrainRouteImport
      parentRoute: typeof BrandsBrandIdRoute
    }
    '/brands/$brandId/review': {
      id: '/brands/$brandId/review'
      path: '/review'
      fullPath: '/brands/$brandId/review'
      preLoaderRoute: typeof BrandsBrandIdReviewRouteImport
      parentRoute: typeof BrandsBrandIdRoute
    }
  }
}

interface BrandsBrandIdRouteChildren {
  BrandsBrandIdBrainRoute: typeof BrandsBrandIdBrainRoute
  BrandsBrandIdReviewRoute: typeof BrandsBrandIdReviewRoute
  BrandsBrandIdIndexRoute: typeof BrandsBrandIdIndexRoute
}

const BrandsBrandIdRouteChildren: BrandsBrandIdRouteChildren = {
  BrandsBrandIdBrainRoute: BrandsBrandIdBrainRoute,
  BrandsBrandIdReviewRoute: BrandsBrandIdReviewRoute,
  BrandsBrandIdIndexRoute: BrandsBrandIdIndexRoute,
}

const BrandsBrandIdRouteWithChildren = BrandsBrandIdRoute._addFileChildren(
  BrandsBrandIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsBrandIdRoute: BrandsBrandIdRouteWithChildren,
  ReviewsCheckIdRoute: ReviewsCheckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
