/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBrandsBrandIdRouteImport } from './routes/_authenticated/brands.$brandId'
import { Route as AuthenticatedReviewsCheckIdRouteImport } from './routes/_authenticated/reviews.$checkId'
import { Route as AuthenticatedBrandsBrandIdIndexRouteImport } from './routes/_authenticated/brands.$brandId.index'
import { Route as AuthenticatedBrandsBrandIdBrainRouteImport } from './routes/_authenticated/brands.$brandId.brain'
import { Route as AuthenticatedBrandsBrandIdReviewRouteImport } from './routes/_authenticated/brands.$brandId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBrandsBrandIdRoute =
  AuthenticatedBrandsBrandIdRouteImport.update({
    id: '/brands/$brandId',
    path: '/brands/$brandId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewsCheckIdRoute =
  AuthenticatedReviewsCheckIdRouteImport.update({
    id: '/reviews/$checkId',
    path: '/reviews/$checkId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsBrandIdIndexRoute =
  AuthenticatedBrandsBrandIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBrandsBrandIdRoute,
  } as any)
const AuthenticatedBrandsBrandIdBrainRoute =
  AuthenticatedBrandsBrandIdBrainRouteImport.update({
    id: '/brain',
    path: '/brain',
    getParentRoute: () => AuthenticatedBrandsBrandIdRoute,
  } as any)
const AuthenticatedBrandsBrandIdReviewRoute =
  AuthenticatedBrandsBrandIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedBrandsBrandIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdRouteWithChildren
  '/reviews/$checkId': typeof AuthenticatedReviewsCheckIdRoute
  '/brands/$brandId/brain': typeof AuthenticatedBrandsBrandIdBrainRoute
  '/brands/$brandId/review': typeof AuthenticatedBrandsBrandIdReviewRoute
  '/brands/$brandId/': typeof AuthenticatedBrandsBrandIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reviews/$checkId': typeof AuthenticatedReviewsCheckIdRoute
  '/brands/$brandId/brain': typeof AuthenticatedBrandsBrandIdBrainRoute
  '/brands/$brandId/review': typeof AuthenticatedBrandsBrandIdReviewRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/brands/$brandId': typeof AuthenticatedBrandsBrandIdRouteWithChildren
  '/_authenticated/reviews/$checkId': typeof AuthenticatedReviewsCheckIdRoute
  '/_authenticated/brands/$brandId/brain': typeof AuthenticatedBrandsBrandIdBrainRoute
  '/_authenticated/brands/$brandId/review': typeof AuthenticatedBrandsBrandIdReviewRoute
  '/_authenticated/brands/$brandId/': typeof AuthenticatedBrandsBrandIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brands/$brandId'
    | '/reviews/$checkId'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/review'
    | '/brands/$brandId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reviews/$checkId'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/review'
    | '/brands/$brandId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/brands/$brandId'
    | '/_authenticated/reviews/$checkId'
    | '/_authenticated/brands/$brandId/brain'
    | '/_authenticated/brands/$brandId/review'
    | '/_authenticated/brands/$brandId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/brands/$brandId': {
      id: '/_authenticated/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews/$checkId': {
      id: '/_authenticated/reviews/$checkId'
      path: '/reviews/$checkId'
      fullPath: '/reviews/$checkId'
      preLoaderRoute: typeof AuthenticatedReviewsCheckIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/$brandId/': {
      id: '/_authenticated/brands/$brandId/'
      path: '/'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdIndexRouteImport
      parentRoute: typeof AuthenticatedBrandsBrandIdRoute
    }
    '/_authenticated/brands/$brandId/brain': {
      id: '/_authenticated/brands/$brandId/brain'
      path: '/brain'
      fullPath: '/brands/$brandId/brain'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdBrainRouteImport
      parentRoute: typeof AuthenticatedBrandsBrandIdRoute
    }
    '/_authenticated/brands/$brandId/review': {
      id: '/_authenticated/brands/$brandId/review'
      path: '/review'
      fullPath: '/brands/$brandId/review'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdReviewRouteImport
      parentRoute: typeof AuthenticatedBrandsBrandIdRoute
    }
  }
}

interface AuthenticatedBrandsBrandIdRouteChildren {
  AuthenticatedBrandsBrandIdBrainRoute: typeof AuthenticatedBrandsBrandIdBrainRoute
  AuthenticatedBrandsBrandIdReviewRoute: typeof AuthenticatedBrandsBrandIdReviewRoute
  AuthenticatedBrandsBrandIdIndexRoute: typeof AuthenticatedBrandsBrandIdIndexRoute
}

const AuthenticatedBrandsBrandIdRouteChildren: AuthenticatedBrandsBrandIdRouteChildren =
  {
    AuthenticatedBrandsBrandIdBrainRoute: AuthenticatedBrandsBrandIdBrainRoute,
    AuthenticatedBrandsBrandIdReviewRoute:
      AuthenticatedBrandsBrandIdReviewRoute,
    AuthenticatedBrandsBrandIdIndexRoute: AuthenticatedBrandsBrandIdIndexRoute,
  }

const AuthenticatedBrandsBrandIdRouteWithChildren =
  AuthenticatedBrandsBrandIdRoute._addFileChildren(
    AuthenticatedBrandsBrandIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandsBrandIdRoute: typeof AuthenticatedBrandsBrandIdRouteWithChildren
  AuthenticatedReviewsCheckIdRoute: typeof AuthenticatedReviewsCheckIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandsBrandIdRoute: AuthenticatedBrandsBrandIdRouteWithChildren,
  AuthenticatedReviewsCheckIdRoute: AuthenticatedReviewsCheckIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
